/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./src/layouts/base.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
