/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Astronaut: typeof import('./src/components/lottie/astronaut.vue')['default']
    Base: typeof import('./src/layouts/base.vue')['default']
    Burger: typeof import('./src/components/burger.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    Email: typeof import('./src/components/lottie/email.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListPosts: typeof import('./src/components/listPosts.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Retro: typeof import('./src/components/retro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search.vue')['default']
    Section: typeof import('./src/components/section.vue')['default']
  }
}
